### ISSUE TITLE
Create a new RC for RIAW

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#168]
This issue is to keep track of where we are with all issues needing to be done before the next RIAW. https://github.com/phetsims/QA/issues/137 was closed, but can be used as a base. 

- [ ] ~we also want to make sure that https://github.com/phetsims/scenery/issues/830#event-1768435041 gets in here.~

**Comment by jessegreenberg** [comment]
With #165 and #164 I don't think that https://github.com/phetsims/scenery/issues/830#event-1768435041 will be required for this release anymore.

**Comment by zepumph** [comment]
- [x] already done, cherry picked this commit https://github.com/phetsims/sun/commit/0ccb537199bef49a6e3dc7090e8a1701e2695741 into sun branch for https://github.com/phetsims/resistance-in-a-wire/issues/160
- [ ] cherry pick https://github.com/phetsims/resistance-in-a-wire/commit/ffcefb6ad36f94f606c878e51b0f8ff86f10f7f3 for https://github.com/phetsims/resistance-in-a-wire/issues/165 which also covers #164.

Looks like we are ready for the next rc after that cherry-pick commit. Good luck us that the merge goes well

**Comment by zepumph** [comment]
qa issue created in phetsims/QA#179
